ckpt_path: null
data:
  class_path: PretraninedABSADataModule
  init_args:
    batch_size: 16
    k2t_file: ./data/knowledge2token.json
    num_workers: 16
    source_train_file: ./processed/dataset/service.train.txt
    t2k_file: ./data/token2knowledge.json
    target: restaurant
    target_train_file: ./processed/dataset/restaurant.train.txt
    use_target: true
model:
  class_path: models.PretrainedFDGRClassifer
  init_args:
    h_dim: 300
    lr: 2e-5
    num_labels: 7
    p: 1.0
seed_everything: 42
trainer:
  accelerator: gpu
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: /root/autodl-tmp/models/service-restaurant/dim=300-max-epoch=30-p=1.0
      filename: pretrained-fdgr
      save_last: true
      save_weights_only: true
      verbose: true
  default_root_dir: /root/autodl-tmp
  enable_progress_bar: true
  log_every_n_steps: 10
  max_epochs: 30
