# lightning.pytorch==2.0.0
seed_everything: 42
model:
  class_path: models.PretrainedFDGRClassifer
  init_args:
    num_labels: 7
    lr: 3e-5
    h_dim: 300
data:
  class_path: PretraninedABSADataModule
  init_args:
    batch_size: 16
    num_workers: 16
    k2t_file: ./data/knowledge2token.json
    t2k_file: ./data/token2knowledge.json
    target: restaurant
    train_file: ./processed/dataset/service.train.txt
trainer:
  accelerator: gpu
  enable_progress_bar: True
  max_epochs: 50
  default_root_dir: /root/autodl-tmp
  log_every_n_steps: 10
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args: 
        verbose: True
        save_weights_only: True
        filename: bert-absa-{epoch:02d}
ckpt_path: null