data:
  class_path: ABSADataModule
  init_args:
    batch_size: 64
    num_workers: 16
    target: laptop
    vad_lexicon: ./NRC-VAD-Lexicon.txt
    test_file: ./processed/dataset/laptop.test.txt
model:
  class_path: models.BertClassifier
  init_args:
    lr: 3e-5
    num_labels: 3
seed_everything: 42
trainer:
  accelerator: gpu
  default_root_dir: /root/autodl-tmp
  enable_progress_bar: true
  log_every_n_steps: 10
  max_epochs: 15
ckpt_path: /root/autodl-tmp/lightning_logs/version_0/checkpoints/bert-alsc-epoch=01-val_f1=0.69.ckpt