data:
  class_path: ABSADataModule
  init_args:
    batch_size: 64
    k2t_file: ./data/knowledge2token.json
    num_workers: 16
    t2k_file: ./data/token2knowledge.json
    target: restaurant
    test_file: ./processed/dataset/restaurant.test.txt
model:
  class_path: models.FDGRClassifer
  init_args:
    lr: 3e-5
    model:
      class_path: model.FDGRModel
      init_args:
        num_labels: 7
        pretrained_path: /root/autodl-tmp/models/laptop-restaurant/dim=300-max-epoch=30-p=0.5/pretrained-fdgr-v1.ckpt
    num_labels: 7
    output_dir: /root/FDGR/out
seed_everything: 42
trainer:
  accelerator: gpu
  default_root_dir: /root/autodl-tmp
  enable_progress_bar: true
  log_every_n_steps: 10
  max_epochs: 15
