data:
  class_path: ABSADataModule
  init_args:
    batch_size: 64
    num_workers: 24
    vad_lexicon_file: ./NRC-VAD-Lexicon.txt
    test_file: ./processed/dataset/restaurant.test.txt
    graph_suffix: .graph
model:
  class_path: models.FDGRClassifer
  init_args:
    coff: 0.02
    lr: 3e-5
    num_labels: 3
seed_everything: 42
trainer:
  accelerator: gpu
  default_root_dir: /root/autodl-tmp
  enable_progress_bar: true
  log_every_n_steps: 10
  max_epochs: 15
