ckpt_path: null
data:
  class_path: ABSADataModule
  init_args:
    batch_size: 16
    num_workers: 1
    target: laptop
    synonyms: ./data/synonyms.json
    vad_lexicon: ./NRC-VAD-Lexicon.txt
    source_train_file: ./processed/dataset/restaurant.train.txt
    target_train_file: ./processed/dataset/laptop.train.txt
    validation_file: ./processed/dataset/restaurant.validation.txt
model:
  class_path: models.BertClassifier
  init_args:
    lr: 2e-5
    num_labels: 3
    output_dir: /root/BERT/out
seed_everything: 42
trainer:
  accelerator: gpu
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      filename: bert-alsc-{epoch:02d}-{val_f1:.2f}
      mode: max
      monitor: val_f1
      save_last: false
      verbose: true
  default_root_dir: /root/autodl-tmp
  enable_progress_bar: true
  log_every_n_steps: 10
  max_epochs: 3
