data:
  class_path: ABSADataModule
  init_args:
    batch_size: 16
    num_workers: 12
    vad_lexicon_file: ./NRC-VAD-Lexicon.txt
    affective_file: ./affectivespace.csv
    train_file: ./processed/dataset/laptop.train.txt
    contrast_file: ./processed/dataset/laptop.contrast.train.txt
    validation_file: ./processed/dataset/laptop.validation.txt
    test_file: ./processed/dataset/twitter.test.txt
    graph_suffix: .graph
model:
  class_path: models.FDGRClassifer
  init_args:
    h_dim: 100
    affective_dim: 100
    coff: 0.1
    lr: 1e-5
    num_labels: 3
seed_everything: 2024
trainer:
  accelerator: gpu
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      filename: fdgr-alsc-{epoch:02d}-{val_f1:.2f}
      mode: max
      monitor: val_f1
      save_last: true
      verbose: true
  default_root_dir: /root/autodl-tmp
  enable_progress_bar: true
  log_every_n_steps: 10
  max_epochs: 15