ckpt_path: null
data:
  class_path: ABSADataModule
  init_args:
    batch_size: 16
    num_workers: 24
    vad_lexicon_file: ./NRC-VAD-Lexicon.txt
    train_file: ./processed/dataset/restaurant.train.txt
    contrast_file: ./processed/dataset/restaurant.contrast.train.txt
    validation_file: ./processed/dataset/restaurant.validation.txt
    graph_suffix: .graph
model:
  class_path: models.FDGRClassifer
  init_args:
    coff: 0.02
    lr: 2e-5
    num_labels: 3
seed_everything: 42
trainer:
  accelerator: gpu
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      filename: fdgr-alsc-{epoch:02d}-{val_f1:.2f}
      mode: max
      monitor: val_f1
      save_last: false
      verbose: true
  default_root_dir: /root/autodl-tmp
  enable_progress_bar: true
  log_every_n_steps: 10
  max_epochs: 15
