ckpt_path: null
data:
  class_path: ABSADataModule
  init_args:
    batch_size: 16
    k2t_file: ./data/knowledge2token.json
    num_workers: 16
    source_train_file: ./processed/dataset/laptop.train.txt
    t2k_file: ./data/token2knowledge.json
    target: restaurant
    target_train_file: ./processed/dataset/restaurant.train.txt
    validation_file: ./processed/dataset/laptop.validation.txt
model:
  class_path: models.FDGRClassifer
  init_args:
    coff: 0.02
    coff_mi: 0.02
    lr: 2e-5
    model:
      class_path: model.FDGRModel
      init_args:
        num_labels: 7
        pretrained_path: /root/autodl-tmp/models/laptop-restaurant/dim=300-max-epoch=30-p=0.5/pretrained-fdgr-v1.ckpt
    num_labels: 7
    output_dir: /root/FDGR/out
seed_everything: 42
trainer:
  accelerator: gpu
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      filename: fdgr-absa-{epoch:02d}-{val_f1:.2f}
      mode: max
      monitor: val_f1
      save_last: false
      verbose: true
  default_root_dir: /root/autodl-tmp
  enable_progress_bar: true
  log_every_n_steps: 10
  max_epochs: 15
